name: Sync to AtomGit

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to AtomGit
        env:
          ATOMGIT_TOKEN: ${{ secrets.ATOMGIT_TOKEN }}
        run: |
          git remote add atomgit "https://gcw_7DpHPfUr:${ATOMGIT_TOKEN}@atomgit.com/soa-userscripts/soa-userscripts.git"
          git push atomgit HEAD:main
          git push atomgit --tags
